# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b270085d038e59fe59ee558fe4dbae6"
name = "remix-app"
application_url = "https://croatia-italian-scanned-vcr.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "developmcs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://croatia-italian-scanned-vcr.trycloudflare.com/auth/callback",
  "https://croatia-italian-scanned-vcr.trycloudflare.com/auth/shopify/callback",
  "https://croatia-italian-scanned-vcr.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
